# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProxyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProxyWindow(object):
    def setupUi(self, ProxyWindow):
        ProxyWindow.setObjectName("ProxyWindow")
        ProxyWindow.resize(773, 402)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ProxyWindow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_proxy = QtWidgets.QTableWidget(ProxyWindow)
        self.tableWidget_proxy.setObjectName("tableWidget_proxy")
        self.tableWidget_proxy.setColumnCount(0)
        self.tableWidget_proxy.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_proxy)

        self.retranslateUi(ProxyWindow)
        QtCore.QMetaObject.connectSlotsByName(ProxyWindow)

    def retranslateUi(self, ProxyWindow):
        _translate = QtCore.QCoreApplication.translate
        ProxyWindow.setWindowTitle(_translate("ProxyWindow", "代理设置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProxyWindow = QtWidgets.QWidget()
    ui = Ui_ProxyWindow()
    ui.setupUi(ProxyWindow)
    ProxyWindow.show()
    sys.exit(app.exec_())
