# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'msf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MSF(object):
    def setupUi(self, MSF):
        MSF.setObjectName("MSF")
        MSF.resize(918, 496)
        MSF.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(MSF)
        self.gridLayout.setContentsMargins(10, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_payload = QtWidgets.QComboBox(MSF)
        self.comboBox_payload.setObjectName("comboBox_payload")
        self.comboBox_payload.addItem("")
        self.comboBox_payload.addItem("")
        self.comboBox_payload.addItem("")
        self.comboBox_payload.addItem("")
        self.gridLayout.addWidget(self.comboBox_payload, 0, 2, 1, 1)
        self.btn_run = QtWidgets.QPushButton(MSF)
        self.btn_run.setObjectName("btn_run")
        self.gridLayout.addWidget(self.btn_run, 0, 3, 1, 2)
        self.textEdit_note = QtWidgets.QTextEdit(MSF)
        self.textEdit_note.setObjectName("textEdit_note")
        self.gridLayout.addWidget(self.textEdit_note, 2, 0, 1, 8)
        self.widget = QtWidgets.QWidget(MSF)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox_port = QtWidgets.QSpinBox(self.widget)
        self.spinBox_port.setMinimum(1)
        self.spinBox_port.setMaximum(65535)
        self.spinBox_port.setObjectName("spinBox_port")
        self.horizontalLayout.addWidget(self.spinBox_port)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget, 1, 3, 1, 4)
        self.label_port = QtWidgets.QLabel(MSF)
        self.label_port.setObjectName("label_port")
        self.gridLayout.addWidget(self.label_port, 0, 0, 1, 1)
        self.label_host = QtWidgets.QLabel(MSF)
        self.label_host.setObjectName("label_host")
        self.gridLayout.addWidget(self.label_host, 1, 0, 1, 1)
        self.lineEdit_host = QtWidgets.QLineEdit(MSF)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.gridLayout.addWidget(self.lineEdit_host, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 6, 1, 1)

        self.retranslateUi(MSF)
        QtCore.QMetaObject.connectSlotsByName(MSF)

    def retranslateUi(self, MSF):
        _translate = QtCore.QCoreApplication.translate
        MSF.setWindowTitle(_translate("MSF", "Form"))
        self.comboBox_payload.setItemText(0, _translate("MSF", "php/meterpreter/reverse_tcp"))
        self.comboBox_payload.setItemText(1, _translate("MSF", "php/meterpreter/bind_tcp"))
        self.comboBox_payload.setItemText(2, _translate("MSF", "php/reverse_php"))
        self.comboBox_payload.setItemText(3, _translate("MSF", "php/bind_php"))
        self.btn_run.setText(_translate("MSF", "Run"))
        self.label_3.setText(_translate("MSF", "LPORT:"))
        self.label_port.setText(_translate("MSF", "payload："))
        self.label_host.setText(_translate("MSF", "LHOST:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MSF = QtWidgets.QWidget()
    ui = Ui_MSF()
    ui.setupUi(MSF)
    MSF.show()
    sys.exit(app.exec_())
