# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenFileInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenFileInfo(object):
    def setupUi(self, OpenFileInfo):
        OpenFileInfo.setObjectName("OpenFileInfo")
        OpenFileInfo.resize(734, 686)
        self.verticalLayout = QtWidgets.QVBoxLayout(OpenFileInfo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(OpenFileInfo)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.layout_editor = QtWidgets.QHBoxLayout(self.widget_2)
        self.layout_editor.setContentsMargins(0, 0, 0, 5)
        self.layout_editor.setSpacing(0)
        self.layout_editor.setObjectName("layout_editor")
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(OpenFileInfo)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_refresh = QtWidgets.QPushButton(self.widget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout.addWidget(self.btn_refresh)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(self.widget)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_cancel = QtWidgets.QPushButton(self.widget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(OpenFileInfo)
        QtCore.QMetaObject.connectSlotsByName(OpenFileInfo)

    def retranslateUi(self, OpenFileInfo):
        _translate = QtCore.QCoreApplication.translate
        OpenFileInfo.setWindowTitle(_translate("OpenFileInfo", "Form"))
        self.btn_refresh.setText(_translate("OpenFileInfo", "刷新"))
        self.btn_save.setText(_translate("OpenFileInfo", "保存"))
        self.btn_cancel.setText(_translate("OpenFileInfo", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OpenFileInfo = QtWidgets.QWidget()
    ui = Ui_OpenFileInfo()
    ui.setupUi(OpenFileInfo)
    OpenFileInfo.show()
    sys.exit(app.exec_())
