# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SqlEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SqlEdit(object):
    def setupUi(self, SqlEdit):
        SqlEdit.setObjectName("SqlEdit")
        SqlEdit.resize(781, 183)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SqlEdit)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(SqlEdit)
        self.widget.setMinimumSize(QtCore.QSize(30, 0))
        self.widget.setMaximumSize(QtCore.QSize(30, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_execute = QtWidgets.QPushButton(self.widget)
        self.btn_execute.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/database/execute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_execute.setIcon(icon)
        self.btn_execute.setObjectName("btn_execute")
        self.verticalLayout_2.addWidget(self.btn_execute)
        self.btn_clear = QtWidgets.QPushButton(self.widget)
        self.btn_clear.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/database/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clear.setIcon(icon1)
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout_2.addWidget(self.btn_clear)
        self.btn_save = QtWidgets.QPushButton(self.widget)
        self.btn_save.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/database/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon2)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_2.addWidget(self.btn_save)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(SqlEdit)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.layout_Editor = QtWidgets.QVBoxLayout(self.widget_2)
        self.layout_Editor.setContentsMargins(0, 0, 0, 0)
        self.layout_Editor.setSpacing(0)
        self.layout_Editor.setObjectName("layout_Editor")
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(SqlEdit)
        QtCore.QMetaObject.connectSlotsByName(SqlEdit)

    def retranslateUi(self, SqlEdit):
        _translate = QtCore.QCoreApplication.translate
        SqlEdit.setWindowTitle(_translate("SqlEdit", "Form"))
        self.btn_execute.setToolTip(_translate("SqlEdit", "执行SQL语句"))
        self.btn_clear.setToolTip(_translate("SqlEdit", "清空SQL编辑框"))
        self.btn_save.setToolTip(_translate("SqlEdit", "保存SQL执行结果到文件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SqlEdit = QtWidgets.QWidget()
    ui = Ui_SqlEdit()
    ui.setupUi(SqlEdit)
    SqlEdit.show()
    sys.exit(app.exec_())
