# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1292, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_main = QtWidgets.QWidget(self.centralwidget)
        self.widget_main.setObjectName("widget_main")
        self.layout_main = QtWidgets.QHBoxLayout(self.widget_main)
        self.layout_main.setObjectName("layout_main")
        self.horizontalLayout_2.addWidget(self.widget_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1292, 26))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_settings = QtWidgets.QMenu(self.menubar)
        self.menu_settings.setObjectName("menu_settings")
        self.menu_tools = QtWidgets.QMenu(self.menubar)
        self.menu_tools.setObjectName("menu_tools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_proxy = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/proxy/proxy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_proxy.setIcon(icon)
        self.action_proxy.setObjectName("action_proxy")
        self.action_http = QtWidgets.QAction(MainWindow)
        self.action_http.setObjectName("action_http")
        self.action_genwebshell = QtWidgets.QAction(MainWindow)
        self.action_genwebshell.setObjectName("action_genwebshell")
        self.action_import = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/other/import"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_import.setIcon(icon1)
        self.action_import.setObjectName("action_import")
        self.action_export = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/other/export"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_export.setIcon(icon2)
        self.action_export.setObjectName("action_export")
        self.action_group = QtWidgets.QAction(MainWindow)
        self.action_group.setObjectName("action_group")
        self.action_exportsetting = QtWidgets.QAction(MainWindow)
        self.action_exportsetting.setObjectName("action_exportsetting")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menu_file.addAction(self.action_import)
        self.menu_file.addAction(self.action_export)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_about)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_settings.addAction(self.action_proxy)
        self.menu_tools.addAction(self.action_genwebshell)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_settings.menuAction())
        self.menubar.addAction(self.menu_tools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TQKnight"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_settings.setTitle(_translate("MainWindow", "设置"))
        self.menu_tools.setTitle(_translate("MainWindow", "工具"))
        self.action_proxy.setText(_translate("MainWindow", "代理设置"))
        self.action_http.setText(_translate("MainWindow", "http头设置"))
        self.action_genwebshell.setText(_translate("MainWindow", "webshell生成"))
        self.action_import.setText(_translate("MainWindow", "导入数据"))
        self.action_export.setText(_translate("MainWindow", "导出数据"))
        self.action_group.setText(_translate("MainWindow", "分组设置"))
        self.action_exportsetting.setText(_translate("MainWindow", "导出配置数据"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.action_exit.setText(_translate("MainWindow", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
