# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'webshellGroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_webshellGroup(object):
    def setupUi(self, webshellGroup):
        webshellGroup.setObjectName("webshellGroup")
        webshellGroup.resize(356, 614)
        self.gridLayout = QtWidgets.QGridLayout(webshellGroup)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_deletegroup = QtWidgets.QPushButton(webshellGroup)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/webshell/groupDel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_deletegroup.setIcon(icon)
        self.btn_deletegroup.setObjectName("btn_deletegroup")
        self.gridLayout.addWidget(self.btn_deletegroup, 0, 2, 1, 1)
        self.btn_addgroup = QtWidgets.QPushButton(webshellGroup)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/webshell/groupAdd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_addgroup.setIcon(icon1)
        self.btn_addgroup.setIconSize(QtCore.QSize(20, 20))
        self.btn_addgroup.setObjectName("btn_addgroup")
        self.gridLayout.addWidget(self.btn_addgroup, 0, 0, 1, 1)
        self.btn_renamegroup = QtWidgets.QPushButton(webshellGroup)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/webshell/groupRename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_renamegroup.setIcon(icon2)
        self.btn_renamegroup.setObjectName("btn_renamegroup")
        self.gridLayout.addWidget(self.btn_renamegroup, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.tree_main = QtWidgets.QTreeWidget(webshellGroup)
        self.tree_main.setHeaderHidden(True)
        self.tree_main.setObjectName("tree_main")
        self.tree_main.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.tree_main, 1, 0, 1, 4)

        self.retranslateUi(webshellGroup)
        QtCore.QMetaObject.connectSlotsByName(webshellGroup)

    def retranslateUi(self, webshellGroup):
        _translate = QtCore.QCoreApplication.translate
        webshellGroup.setWindowTitle(_translate("webshellGroup", "Form"))
        self.btn_deletegroup.setToolTip(_translate("webshellGroup", "删除分组"))
        self.btn_deletegroup.setText(_translate("webshellGroup", "删除分组"))
        self.btn_addgroup.setToolTip(_translate("webshellGroup", "添加分组"))
        self.btn_addgroup.setText(_translate("webshellGroup", "新建分组"))
        self.btn_renamegroup.setToolTip(_translate("webshellGroup", "重命名分组"))
        self.btn_renamegroup.setText(_translate("webshellGroup", "重命名分组"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    webshellGroup = QtWidgets.QWidget()
    ui = Ui_webshellGroup()
    ui.setupUi(webshellGroup)
    webshellGroup.show()
    sys.exit(app.exec_())
